version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./app:/app
    php:
        build:
            context: ./docker/php
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
            - ./docker/php/config:/usr/local/etc/php 
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
       image: 'phpmyadmin:latest'
       ports:
          - 8080:80
       environment:
          - PMA_ARBITRARY=1
       depends_on:
          - mysql
volumes:
    mysqldata: {}
